config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  #START Resque
  mount Resque::Server.new, at: "/resque"

  #END Resque

  resources :tasks
  resources :tasks
  resources :projects

  namespace :admin do
    root to: "application#index"
    resources :projects do
      resources :tickets
    end
    resources :tests
    resources :users do
      patch :archive, on: :member
    end
  end
  devise_for :users

  namespace :api, defaults: {format: :json} do
    devise_for :users
    namespace :v1 do
      resources :tests, only: [:show, :index]
      resources :users, only: [:show]
      resources :sessions, :only => [:create, :destroy]
      resources :test_results, only: [:create, :update]
    end
  end


  namespace :api do
    resources :crawlers
    post "crawl_data", as: :crawl_data, to: "crawlers#crawl_data"
  end


  root to: "home#index"

end

# Routes
# get '/undead', to: redirect('/zombies')

# "link_name" to "action_name" as "zombie_path"
# get '/all', to: 'zombies#index', as: zombie

# "root" localhost:3000/
# root to: 'zombies#index'
#
# get :decomp, on: :member => /zombies/:id/decomp specify 1 member :id
# get :decomp_group, on: :collection => /zombies/decomp_group specify a group contain a lot member

# <%= link_to 'All Zombies', zombies_path %>
#     <%= link_to 'New Zombie', new_zombie_path %>
#     <%= link_to 'Edit Zombie', edit_zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', @zombie %>
#     <%= link_to 'Delete Zombie', @zombie, method: :delete %>
#
#
#     Nested Route
#     <% @tweets.each do |tweet| %>
#         <tr>
#           <td><%= tweet.body %></td>
#           <td><%= link_to 'Show', [@zombie, tweet] %></td>
#           <td><%= link_to 'Edit', edit_zombie_tweet_path(@zombie, tweet) %></td>
#           <td><%= link_to 'Destroy', [@zombie, tweet], method: :delete %></td>
#         </tr>
#     <% end %>
#     <%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :name, presence: true
  has_many :tickets, dependent: :destroy #delete_all just use SQL DELETE, not check validate
  has_many :roles, dependent: :delete_all


  # Test-Prescriptions-Rspec-Ebook
  def done?
    incomplete_tasks.empty?
  end

  def remaining_size
    incomplete_tasks.sum(&:size)
  end

  def total_size
    tasks.to_a.sum(&:size)
  end

  # calculate
  def completed_velocity
    tasks.to_a.sum(&:points_toward_velocity)
  end


  def current_rate
    completed_velocity * 1.0 / Project.velocity_length_in_days
  end

  def projected_days_remaining
    remaining_size / current_rate
  end

  def on_schedule?
    return false if projected_days_remaining.nan?
    (Date.today + projected_days_remaining) <= due_date
  end

  private
  def incomplete_tasks
    tasks.to_a.reject(&:completed?)
  end

  def self.velocity_length_in_days
    21
  end

end

app/controllers/admin/projects_controller.rb
module Admin
  class Admin::ProjectsController < Admin::ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    # GET /admin/projects
    def index
      @projects = ::Project.all
    end

    # GET /admin/projects/1
    def show
      authorize @project, :show?
    end

    # GET /admin/projects/new
    def new
      @project = ::Project.new
    end

    # GET /admin/projects/1/edit
    def edit
    end

    # POST /admin/projects
    def create
      @project = ::Project.new(project_params)
      if @project.save
        redirect_to [:admin, @project], notice: 'Project was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/projects/1
    def update
      if @project.update(project_params)
        redirect_to [:admin, @project], notice: 'Project was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/projects/1
    def destroy
      @project.destroy
      redirect_to admin_projects_url, notice: 'Project was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = ::Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to admin_projects_path
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :description, :id)
    end
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= simple_form_for([:admin, @project], :html => {:role => "form"}) do |f| %>
          <%= render partial: "layouts/error_message", :locals => {object: @project} %>
          <%= f.input :name, input_html: {class: "form-control"} %>
          <%= f.input :description, input_html: {class: "form-control"} %>
          <%= f.submit :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/projects/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      Editing <small><%= link_to "Project", edit_admin_project_path(@project)  %></small>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Projects", admin_projects_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/admin/projects/index.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>Listing
        <small>Projects</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">admin_projects</li>
      </ol>
    </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_admin_project_path(@project), :class => 'btn btn-success' do %>
                <span class="glyphicon glyphicon-plus"></span>
                New Project
            <% end %>
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <%= content_tag_for(:tr, @projects) do |project| %>
                <td><%= link_to project.name, admin_project_path(project) %></td>
                <td><%= project.description %></td>
                <td>
                  <%= link_to 'Edit', edit_admin_project_path(project) %>
                  <%= link_to 'Destroy', admin_project_path(project), method: :delete, data: {confirm: 'Are you sure?'} %>
                </td>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/projects/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>admin_project</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "admin_projects", admin_projects_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/admin/projects/show.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>Show
        <small>admin_project</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Admin_projects", admin_projects_path %></li>
        <li class="active">Show</li>
      </ol>
    </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_admin_project_path(@project), :class => 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-pencil"></span>
                Edit Project
            <% end %>
            <%= link_to new_admin_project_ticket_path(@project), :class => 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-list"></span>
                New Ticket
            <% end %>
            <%= link_to admin_project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} do %>
                <span class="glyphicon glyphicon-trash"></span>
                Delete Project
            <% end %>

          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd><%= @project.name %></dd>
            <dt>Description</dt>
            <dd><%= @project.description %></dd>
          </dl>
          <ul id="tickets">
            <% @project.tickets.each do |ticket| %>
                <li>
                  #<%= ticket.id %> -
                  <%= link_to ticket.name, [:admin, @project, ticket] %>
                </li>
                <tr>
                  <th>Author:</th>
                  <td><%= ticket.author.email %></td>
                </tr>
                <tr>
                  <th>Created:</th>
                  <td><%= time_ago_in_words(ticket.created_at) %> ago</td>
                </tr>

            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>