config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  #START Resque
  mount Resque::Server.new, at: "/resque"

  #END Resque

  resources :tasks
  resources :tasks
  resources :projects

  namespace :admin do
    root to: "application#index"
    resources :projects do
      resources :tickets
    end
    resources :tests
    resources :users do
      patch :archive, on: :member
    end
  end
  devise_for :users

  namespace :api, defaults: {format: :json} do
    devise_for :users
    namespace :v1 do
      resources :tests, only: [:show, :index]
      resources :users, only: [:show]
      resources :sessions, :only => [:create, :destroy]
      resources :test_results, only: [:create, :update]
    end
  end


  namespace :api do
    resources :crawlers
    post "crawl_data", as: :crawl_data, to: "crawlers#crawl_data"
  end


  root to: "home#index"

end

# Routes
# get '/undead', to: redirect('/zombies')

# "link_name" to "action_name" as "zombie_path"
# get '/all', to: 'zombies#index', as: zombie

# "root" localhost:3000/
# root to: 'zombies#index'
#
# get :decomp, on: :member => /zombies/:id/decomp specify 1 member :id
# get :decomp_group, on: :collection => /zombies/decomp_group specify a group contain a lot member

# <%= link_to 'All Zombies', zombies_path %>
#     <%= link_to 'New Zombie', new_zombie_path %>
#     <%= link_to 'Edit Zombie', edit_zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', @zombie %>
#     <%= link_to 'Delete Zombie', @zombie, method: :delete %>
#
#
#     Nested Route
#     <% @tweets.each do |tweet| %>
#         <tr>
#           <td><%= tweet.body %></td>
#           <td><%= link_to 'Show', [@zombie, tweet] %></td>
#           <td><%= link_to 'Edit', edit_zombie_tweet_path(@zombie, tweet) %></td>
#           <td><%= link_to 'Destroy', [@zombie, tweet], method: :delete %></td>
#         </tr>
#     <% end %>
#     <%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  validates :name, :description, presence: true
  belongs_to :author, class_name: "User"
end

app/controllers/admin/tickets_controller.rb
module Admin
  class TicketsController < ApplicationController
    before_action :set_project # Have to place :set_project before :set_admin_ticket
    before_action :set_admin_ticket, only: [:show, :edit, :update, :destroy]

    # GET /admin/tickets
    def index
      @admin_tickets = ::Ticket.all
    end

    # GET /admin/tickets/1
    def show
    end

    # GET /admin/tickets/new
    def new
      @ticket = @project.tickets.build
    end

    # GET /admin/tickets/1/edit
    def edit
    end

    # POST /admin/tickets
    def create
      @ticket = @project.tickets.build(admin_ticket_params)
      @ticket.author = current_user
      if @ticket.save
        redirect_to [:admin, @project], notice: 'Ticket was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/tickets/1
    def update
      @ticket.author = current_user
      if @ticket.update(admin_ticket_params)
        redirect_to [:admin, @project], notice: 'Ticket was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/tickets/1
    def destroy
      @ticket.destroy
      redirect_to admin_project_url(@project), notice: 'Ticket was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_ticket
      @ticket = @project.tickets.find(params[:id])
    end

    def set_project
      @project = ::Project.find(params[:project_id])
    end
    # Only allow a trusted parameter "white list" through.
    def admin_ticket_params
      params.require(:ticket).permit(:name, :description, :project_id)
    end
  end
end

app/helpers/admin/tickets_helper.rb
module Admin::TicketsHelper
end

app/views/admin/tickets/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= simple_form_for([:admin, @project, @ticket]) do |f| %>
          <%= render partial: "layouts/error_message", :locals => {object: @ticket} %>
          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.association :project %>
          </div>

          <div class="form-actions">
            <%= f.button :submit %>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/tickets/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Tickets", admin_project_path(@project) %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/admin/tickets/index.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Listing <small>admin_tickets</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">admin_tickets</li>
    </ol>    
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_admin_ticket_path(@admin_ticket), :class => 'btn btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Ticket
            <% end %>          
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Project</th>
                            <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @admin_tickets) do |admin_ticket| %>
              <td><%= admin_ticket.name %></td>
              <td><%= admin_ticket.description %></td>
              <td><%= admin_ticket.project %></td>
                            <td><%= link_to 'Show', admin_ticket %></td>
                <td><%= link_to 'Edit', edit_admin_ticket_path(admin_ticket) %></td>
                <td><%= link_to 'Destroy', admin_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/tickets/new.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>New
        <small>admin_ticket</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Tickets", admin_project_tickets_path %></li>
        <li class="active">New</li>
      </ol>
    </section>
<% end %>

<%= render 'form' %>

app/views/admin/tickets/show.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>Show
        <small>Ticket</small>
      </h1>
      <ul class="actions">
        <li><%= link_to "Edit Ticket", edit_admin_project_ticket_path(@project, @ticket),
                        class: "pull-right btn btn-primary" %></li>
        <li><%= link_to "Delete Ticket", admin_project_ticket_path(@project, @ticket), method: :delete,
                        class: "pull-right btn btn-primary" %></li>
      </ul>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Tickets", admin_project_tickets_path %></li>
        <li class="active">Show</li>
      </ol>


    </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-body">
          <div id="ticket">
            <h2><%= @project.name %> </h2>
            <dl class="dl-horizontal">
              <dt>Name:</dt>
              <dd><%= @ticket.name %></dd>

              <dt>Description:</dt>
              <dd><%= simple_format(@ticket.description) %></dd>

              <dt>Project:</dt>
              <dd><%= @project.name %></dd>

            </dl>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>