config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  #START Resque
  mount Resque::Server.new, at: "/resque"

  #END Resque

  resources :tasks
  resources :tasks
  resources :projects

  namespace :admin do
    root to: "application#index"
    resources :projects do
      resources :tickets
    end
    resources :tests
    resources :users do
      patch :archive, on: :member
    end
  end
  devise_for :users

  namespace :api, defaults: {format: :json} do
    devise_for :users
    namespace :v1 do
      resources :tests, only: [:show, :index]
      resources :users, only: [:show]
      resources :sessions, :only => [:create, :destroy]
      resources :test_results, only: [:create, :update]
    end
  end


  namespace :api do
    resources :crawlers
    post "crawl_data", as: :crawl_data, to: "crawlers#crawl_data"
  end


  root to: "home#index"

end

# Routes
# get '/undead', to: redirect('/zombies')

# "link_name" to "action_name" as "zombie_path"
# get '/all', to: 'zombies#index', as: zombie

# "root" localhost:3000/
# root to: 'zombies#index'
#
# get :decomp, on: :member => /zombies/:id/decomp specify 1 member :id
# get :decomp_group, on: :collection => /zombies/decomp_group specify a group contain a lot member

# <%= link_to 'All Zombies', zombies_path %>
#     <%= link_to 'New Zombie', new_zombie_path %>
#     <%= link_to 'Edit Zombie', edit_zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', @zombie %>
#     <%= link_to 'Delete Zombie', @zombie, method: :delete %>
#
#
#     Nested Route
#     <% @tweets.each do |tweet| %>
#         <tr>
#           <td><%= tweet.body %></td>
#           <td><%= link_to 'Show', [@zombie, tweet] %></td>
#           <td><%= link_to 'Edit', edit_zombie_tweet_path(@zombie, tweet) %></td>
#           <td><%= link_to 'Destroy', [@zombie, tweet], method: :delete %></td>
#         </tr>
#     <% end %>
#     <%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_authentication_token!

  scope :excluding_archived, -> { where(archived_at: nil)}

  def archive
    self.update(archived_at: Time.now)
  end

  def not_archived?
    archived_at.nil?
  end
  def active_for_authentication?
    # Custom condition active or not.
    super && not_archived?
  end

  def inactive_message
    # detect error message :inactive or :archived in devise.en.yml
    not_archived? ? super : :archived
  end

  def generate_authentication_token!
    self.auth_token = SecureRandom.hex(16)
    # self.update_column(:api_key, SecureRandom.hex(16))
  end
  # before_create :set_auth_token
  #

  # private
  # def set_auth_token
  #   return if auth_token.present?
  #   self.auth_token = generate_auth_token
  # end
  #
  # def generate_auth_token
  #   loop do
  #     token = SecureRandom.hex
  #     break token unless self.class.exists?(auth_token: token)
  #   end
  # end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:archive, :show, :edit, :update, :destroy]

  def archive
    if @user == current_user
      flash[:notice] = "You cannot archive yourself!"
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end
    redirect_to admin_users_path
  end

  def index
    @users = User.order(id: "desc").excluding_archived
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    User.transaction do
      if @user.update(user_params)
        flash[:notice] = "User has been updated."
        redirect_to admin_users_path
      else
        flash.now[:alert] = "User has not been updated."
        render "edit"
        raise ActiveRecord::Rollback
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= simple_form_for([:admin, @user], :html => {:role => "form"}) do |f| %>
          <%= render partial: "layouts/error_message", locals: {object: @user} %>
          <%= f.input :username %>
          <%= f.input :email %>
          <%= f.input :password, autocomplete: "off" %>
          <%= f.input :password_confirmation, autocomplete: "off" %>
          <%= f.input :admin, label: "Is an admin?", autocomplete: "off" %>
          <%= f.submit :class => "btn btn-flat bg-olive" %>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/users/destroy.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Admin::Users <small>#destroy</small></h1>
  </section>
<% end %>

<section class="content invoice">
  <p>Find me in app/views/admin/users/destroy.html.erb</p>
</section>

app/views/admin/users/edit.html.erb
<% content_for :content_header  do %>
    <section class="content-header">
      <h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><%= link_to "Admin Users", admin_users_path %></li>
          <li class="active">Edit</li>
        </ol>
      </h1>
    </section>
<% end %>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>Listing
        <small>users</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/app/assets/images"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">users</li>
      </ol>
    </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_admin_user_path, :class => 'btn btn-flat bg-olive' do %>
                <span class="glyphicon glyphicon-plus"></span>
                New User
            <% end %>
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Username</th>
              <th>Email</th>
              <th>Admin</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <%= content_tag_for(:tr, @users) do |user| %>
                <td><%= user.username %></td>
                <td>
                  <%= link_to user.email, [:admin, user] %>
                </td>
                <% if user.admin? %>
                    <td><span class="label label-warning">Teacher</span></td>
                <% else %>
                    <td><span class="label label-success">Student</span></td>
                <% end %>
                <td>

                  <%= link_to edit_admin_user_path(user), class: "btn btn-default btn-flat" do %>
                      <i class="glyphicon glyphicon-pencil"></i>
                  <% end %>

                  <%= link_to [:admin, user], class: "btn btn-danger btn-flat", method: :delete, data: {confirm: 'Are you sure?'} do %>
                      <i class="glyphicon glyphicon-trash"></i>
                  <% end %>
                </td>

            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/new.html.erb
<% content_for :content_header  do %>
    <section class="content-header">
      <h1>New <small>User</small></h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "User", admin_users_path %></li>
        <li class="active">New</li>
      </ol>
    </section>
<% end %>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>Show
        <small>user</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Users", admin_users_path %></li>
        <li class="active">Show</li>
      </ol>
    </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_admin_user_path(@user), :class => 'btn btn-flat bg-olive' do %>
                <span class="glyphicon glyphicon-pencil"></span>
                Edit User
            <% end %>
            <%= link_to archive_admin_user_path(@user), method: :patch, :class => 'btn btn-flat bg-orange' do %>
                <span class="glyphicon glyphicon-trash"></span>
                Archive User
            <% end %>
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Name:</dt>
            <dd><%= @user.username %></dd>

            <dt>Email:</dt>
            <dd><%= @user.email %></dd>
          </dl>
        </div>

      </div>
    </div>
  </div>
</section>