config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  #START Resque
  mount Resque::Server.new, at: "/resque"

  #END Resque

  resources :tasks
  resources :tasks
  resources :projects

  namespace :admin do
    root to: "application#index"
    resources :projects do
      resources :tickets
    end
    resources :tests
    resources :users do
      patch :archive, on: :member
    end
  end
  devise_for :users

  namespace :api, defaults: {format: :json} do
    devise_for :users
    namespace :v1 do
      resources :tests, only: [:show, :index]
      resources :users, only: [:show]
      resources :sessions, :only => [:create, :destroy]
      resources :test_results, only: [:create, :update]
    end
  end


  namespace :api do
    resources :crawlers
    post "crawl_data", as: :crawl_data, to: "crawlers#crawl_data"
  end


  root to: "home#index"

end

# Routes
# get '/undead', to: redirect('/zombies')

# "link_name" to "action_name" as "zombie_path"
# get '/all', to: 'zombies#index', as: zombie

# "root" localhost:3000/
# root to: 'zombies#index'
#
# get :decomp, on: :member => /zombies/:id/decomp specify 1 member :id
# get :decomp_group, on: :collection => /zombies/decomp_group specify a group contain a lot member

# <%= link_to 'All Zombies', zombies_path %>
#     <%= link_to 'New Zombie', new_zombie_path %>
#     <%= link_to 'Edit Zombie', edit_zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', zombie_path(@zombie) %>
#     <%= link_to 'Show Zombie', @zombie %>
#     <%= link_to 'Delete Zombie', @zombie, method: :delete %>
#
#
#     Nested Route
#     <% @tweets.each do |tweet| %>
#         <tr>
#           <td><%= tweet.body %></td>
#           <td><%= link_to 'Show', [@zombie, tweet] %></td>
#           <td><%= link_to 'Edit', edit_zombie_tweet_path(@zombie, tweet) %></td>
#           <td><%= link_to 'Destroy', [@zombie, tweet], method: :delete %></td>
#         </tr>
#     <% end %>
#     <%= link_to 'New Tweet', new_zombie_tweet_path(@zombie) %>

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :name, presence: true
end

app/models/archive.rb
class Archive
  @queue = :file_serve

  def self.perform(repo_id, branch = 'master')
    puts "Miracleeeeeeee"
    repo = Repository.find(repo_id)
    repo.create_archive(branch)
  end
end

app/models/crawler.rb
class Crawler < ActiveRecord::Base

  validates :url, presence: true

  def crawl_data
    data = Nokogiri::HTML(open(url))
    self.h1_content = data.css('h1').text
    self.h2_content = data.css('h2').text
    self.h3_content = data.css('h3').text
    self.link_content = data.css('a').map { |link| link['href'] }
  end


end

app/models/metaprograming.rb
class Metaprograming
  class  ExploreCollection
    attr_accessor :words

    def initialize
      self.words = %w{ Mary had a little lamb }
    end
    def index_for( word )
      self.words.find_index { |this_word|  word == this_word }
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :name, presence: true
  has_many :tickets, dependent: :destroy #delete_all just use SQL DELETE, not check validate
  has_many :roles, dependent: :delete_all


  # Test-Prescriptions-Rspec-Ebook
  def done?
    incomplete_tasks.empty?
  end

  def remaining_size
    incomplete_tasks.sum(&:size)
  end

  def total_size
    tasks.to_a.sum(&:size)
  end

  # calculate
  def completed_velocity
    tasks.to_a.sum(&:points_toward_velocity)
  end


  def current_rate
    completed_velocity * 1.0 / Project.velocity_length_in_days
  end

  def projected_days_remaining
    remaining_size / current_rate
  end

  def on_schedule?
    return false if projected_days_remaining.nan?
    (Date.today + projected_days_remaining) <= due_date
  end

  private
  def incomplete_tasks
    tasks.to_a.reject(&:completed?)
  end

  def self.velocity_length_in_days
    21
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :test
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true

  validates_associated :answers
  validates :name, presence: true

end

app/models/repository.rb
class Repository
  def async_create_archive(branch)
    Resque.enqueue(Archive, self.id, branch)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/sleeper.rb
class Sleeper
  @queue = :sleep

  def self.perform(seconds)
    puts 'asdsadsad231'
    5 + seconds
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  def completed?
    completed_at.present?
  end

  def mark_completed(completed_at = nil)
    self.completed_at = (completed_at || Time.current)
  end

  def part_of_velocity?
    return false unless completed?
    completed_at > Project.velocity_length_in_days.days.ago
  end

  def points_toward_velocity
    return size if part_of_velocity?
    return 0
  end
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
  validates :name, presence: true
  validates_associated :questions
end

app/models/test_result.rb
class TestResult < ActiveRecord::Base
  belongs_to :question, required: true
  belongs_to :test
  belongs_to :user, required: true
  belongs_to :answer

  validates :question_id, :test_id, :user_id, :answer_id, presence: true
  validates_uniqueness_of :question_id, scope: :user_id
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  validates :name, :description, presence: true
  belongs_to :author, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_authentication_token!

  scope :excluding_archived, -> { where(archived_at: nil)}

  def archive
    self.update(archived_at: Time.now)
  end

  def not_archived?
    archived_at.nil?
  end
  def active_for_authentication?
    # Custom condition active or not.
    super && not_archived?
  end

  def inactive_message
    # detect error message :inactive or :archived in devise.en.yml
    not_archived? ? super : :archived
  end

  def generate_authentication_token!
    self.auth_token = SecureRandom.hex(16)
    # self.update_column(:api_key, SecureRandom.hex(16))
  end
  # before_create :set_auth_token
  #

  # private
  # def set_auth_token
  #   return if auth_token.present?
  #   self.auth_token = generate_auth_token
  # end
  #
  # def generate_auth_token
  #   loop do
  #     token = SecureRandom.hex
  #     break token unless self.class.exists?(auth_token: token)
  #   end
  # end

end

app/helpers/crawlers_helper.rb
module CrawlersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def nav_link(page, &link_text) 
    class_name = request.env['PATH_INFO'].match(page) ? 'active' : nil

    content_tag(:li, class: class_name) do
      link_to page do
        link_text.call
      end
    end
  end

  def treeview_link(text, &links)
    content = link_to('#') do
      content_tag(:span, text) <<
      content_tag(:i, '', class: "fa pull-right fa-angle-left")
    end

    content << content_tag(:ul, class: 'treeview-menu') do 
      links.call
    end

    content_tag :li, class: 'treeview' do
      content
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_application_header.html.erb
<header class="header">
  <a href="#" class="logo">
    <!-- Add the class icon to your logo image or logo icon to add the margining -->
    AdminLTE
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope"></i>
            <span class="label label-success">4</span>
          </a>
        </li>
        <% unless user_signed_in? %>
            <li class="<%= "active" if current_page?("/users/sign_up") %>">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="<%= "active" if current_page?("/users/sign_in") %>">
              <%= link_to "Sign in", new_user_session_path %>
            </li>

        <% else %>
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i>
                <span><%= current_user.email %> <i class="caret"></i></span>
              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header bg-light-blue">
                  <p>Signed in as <%= current_user.email %></p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <%= link_to edit_admin_user_path(current_user), class: "btn btn-primary btn-flat" do %>
                        Profile
                    <% end %>
                  </div>
                  <div class="pull-right">
                    <%= button_to "Sign out", destroy_user_session_path, method: "delete", class: "btn btn-warning btn-flat" %>
                  </div>
                </li>
              </ul>
            </li>

            <li class="<%= "active" if current_page?("/") %>">
              <%= link_to "Home", root_path %>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_application_sidebar.html.erb
<section class="sidebar">
  <!-- Sidebar user panel -->
  <div class="user-panel">
    <div class="pull-left image">
      <img src="/img/avatar.png" class="img-circle" alt="User Image" />
    </div>
    <div class="pull-left info">
      <p>Hello, Luc</p>

      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>
  <!-- search form -->
  <form action="#" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search..."/>
      <span class="input-group-btn">
        <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
  <!-- /.search form -->
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
    <%= nav_link root_path do %>
      <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    <% end %>
    <%= nav_link admin_users_url do %>
        <i class="fa fa-angle-double-right"></i>
        Users
    <% end %>
    <%= nav_link admin_tests_url do %>
        <i class="fa fa-angle-double-right"></i>
        Tests
    <% end %>
    <%= nav_link admin_projects_path do %>
        <i class="fa fa-angle-double-right"></i>
        Projects
    <% end %>
  </ul>
</section>

app/views/layouts/_error_message.html.erb
<!-- object as @project @answer ... -->
<% if object.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      <h4><%= pluralize(object.errors.count, "error") %> prohibited this admin_project from being
        saved:</h4>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <meta name="description" content="">
  <meta name="author" content="">
  <title>AdminLTE::Dashboard</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-black">

  <%= render "layouts/application_header" %>

  <div class="wrapper row-offcanvas row-offcanvas-left">
    <aside class="left-side sidebar-offcanvas">
      <%= render "layouts/application_sidebar" %>
    </aside>
    <aside class="right-side">
      <%= yield(:content_header) %>

      <% flash.each do |name, msg| %>
        <div class="pad margin no-print">
          <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <%= msg %>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
    </aside>
  </div>

  <div class="spinner no-print hidden">
    <img src="/img/ajax-loader.gif" alt="">
  </div>

</body>
</html>